version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
    command: ["/app/main"]

  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GO111MODULE=on
    command: ["go", "test", "./controllers"]  # Runs tests in the controllers directory
    depends_on:
      - app  # Ensure the app service is running before testing
